"""add timestamp column in job table

Revision ID: 7db8dfedcbff
Revises: 5e9e776a2ac6
Create Date: 2026-09-07 18:59:05.491434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db8dfedcbff'
down_revision: Union[str, Sequence[str], None] = '5e9e776a2ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'next_attempt_at')
    # ### end Alembic commands ###
